name: CI Pipeline

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs to run
jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Julia
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'  # Specify the Julia version to use

      # Install dependencies
      - name: Install dependencies
        run: |
          julia --project=@. -e 'using Pkg; Pkg.instantiate()'

      # Run tests
      - name: Run tests
        run: |
          julia --project=@. -e 'using Pkg; Pkg.test()'